# Generated by Django 4.2 on 2023-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_role_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("A", "Author"), ("E", "Editor")], default="A", max_length=1
            ),
        ),
    ]
