# Generated by Django 4.2 on 2023-09-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("d", "Draft"), ("p", "Published")],
                default="d",
                max_length=100,
            ),
        ),
    ]
