# Generated by Django 4.2 on 2023-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created",), "verbose_name_plural": "Post"},
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
